### ISSUE TITLE
How to start Epivizr for S. cerevisiae?

### ISSUE THREAD

**Issue by ewallace** [epiviz/epivizr#6]
Hi,
I am enthusiastic about the idea of Epiviz but am having trouble getting it set up for S. cerevisiae. My problem is that I can neither
(a) start epivizr using a S cerevisiae
(b) start epivizv using a seqinfo object, or otherwise without an OrganismDb

It would be great if you could show me how to fix this, or even expand the help files to make starting with other genomes clearer.

I've attempted to include a reproducible example below.

Many Thanks
Edward Wallace

```
## This works for me, using Mus.musculus OrganismDb
library(epivizr)
library(Mus.musculus)
mgr <- epivizr::startStandalone(Mus.musculus,
                                geneInfoName = "mm10",
                                keepSeqlevels=c("chrX","chrY"))
mgr$stopServer()


## How I make the S.cerevisiae OrganismDb package:
library(org.Sc.sgd.db)
library(TxDb.Scerevisiae.UCSC.sacCer3.sgdGene)
gd <- list(join1 = c(GO.db="GOID", 
                            org.Sc.sgd.db="GO"),
                  join2 = c(org.Sc.sgd.db="ENTREZID",
                            TxDb.Scerevisiae.UCSC.sacCer3.sgdGene="GENEID"))

destination <- tempfile()
dir.create(destination)
makeOrganismPackage(pkgname = "S.cerevisiae",
                    graphData = gd,
                    organism = "S.cerevisiae",
                    version = "1.0.0",
                    maintainer = "E Wallace<ewjwallace@gmail.com>",
                    author = "E Wallace, from SGD packages",
                    destDir = destination,
                    license = "Artistic-2.0")

install.packages(paste0(destination,"/S.cerevisiae"), repos = NULL, type="source")

## load S.cerevisiae
library(S.cerevisiae)

## attempt to start standalone epiviz with S.cerevisiae give error messages"
mgr <- epivizr::startStandalone(geneInfo=S.cerevisiae,
                                    geneInfoName = "SacCer3",
                                keepSeqlevels=c("chrI","chrVI"))

```

> [epivizr] loading standalone from /Library/Frameworks/R.framework/Versions/3.2/Resources/library/epivizr/www
> [epivizr] creating gene annotation:
> [epivizr] error adding geneInfo device: Error in .testForValidCols(x, cols): Invalid columns: SYMBOL. Please use the columns method to see a listing of valid arguments.
> 
> Error in mgr$getRows(msgData$seqName, msgData$start, msgData$end, msgData$metadata,  : 
>   cannot find datasourceepivizMs_geneInfo_1
> Error in mgr$getRows(msgData$seqName, msgData$start, msgData$end, msgData$metadata,  : 
>   cannot find datasourceepivizMs_geneInfo_1
> Error in mgr$getRows(msgData$seqName, msgData$start, msgData$end, msgData$metadata,  : 
>   cannot find datasourceepivizMs_geneInfo_1
> ERROR: [on_request_read] connection reset by peer

```
## Since connection is reset, I can't stop the server and have to restart R session
mgr$stopServer()
Error in .self$waitToClearRequests() : requests not cleared

## note that SYMBOL isn't a column of S.cerevisiae, but I think SGD fulfils the same role
columns(S.cerevisiae)
```

>  [1] "ALIAS"        "CDSCHROM"     "CDSEND"       "CDSID"        "CDSNAME"      "CDSSTART"  
>  [7] "CDSSTRAND"    "COMMON"       "DEFINITION"   "DESCRIPTION"  "ENSEMBL"      "ENSEMBLPROT" 
> [13] "ENSEMBLTRANS" "ENTREZID"     "ENZYME"       "EVIDENCE"     "EVIDENCEALL"  "EXONCHROM"  
> [19] "EXONEND"      "EXONID"       "EXONNAME"     "EXONRANK"     "EXONSTART"    "EXONSTRAND"  
> [25] "GENEID"       "GENENAME"     "GO"           "GOALL"        "GOID"         "INTERPRO"  
> [31] "ONTOLOGY"     "ONTOLOGYALL"  "ORF"          "PATH"         "PFAM"         "PMID"  
> [37] "REFSEQ"       "SGD"          "SMART"        "TERM"         "TXCHROM"      "TXEND"  
> [43] "TXID"         "TXNAME"       "TXSTART"      "TXSTRAND"     "TXTYPE"       "UNIPROT"  

```
## Starting from seqinfo object also does not work. The browser window gives a spinning wait cursor of death, without loading anything, but does not disconnect.
mgr <- epivizr::startStandalone(seqinfo=Seqinfo(genome="sacCer3"))
```

> [epivizr] loading standalone from /Library/Frameworks/R.framework/Versions/3.2/Resources/library/epivizr/www
> Error in mgr$getRows(msgData$seqName, msgData$start, msgData$end, msgData$metadata,  : 
>   cannot find datasourceepivizMs_geneInfo_1
> Error in mgr$getRows(msgData$seqName, msgData$start, msgData$end, msgData$metadata,  : 
>   cannot find datasourceepivizMs_geneInfo_1
> Error in mgr$getRows(msgData$seqName, msgData$start, msgData$end, msgData$metadata,  : 
>   cannot find datasourceepivizMs_geneInfo_1

**Comment by hcorrada** [comment]
Thanks! We are in the middle of a rearrangement of the epivizr package, with epivizrStandalone as a separate package to support this. This will be released later this week. Let's see how this works on the new package and go from there.

**Comment by ewallace** [comment]
Thank you, I will look forward to the new release and beta-test it!

On Wed, Apr 6, 2016 at 11:16 AM, hcorrada <notifications@github.com> wrote:

> Thanks! We are in the middle of a rearrangement of the epivizr package,
> with epivizrStandalone as a separate package to support this. This will be
> released later this week. Let's see how this works on the new package and
> go from there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/epiviz/epivizr/issues/6#issuecomment-206289551>
>



-- 
Edward Wallace, Ph.D.
Marie Skłodowska-Curie Research Fellow
University of Edinburgh
USA: +1-773-517-4009
UK: +44-777-914-7542

**Comment by mschatz** [comment]
Is this working? Im interested to use epiviz for a plant species and wondering if this is supported

**Comment by hcorrada** [comment]
Yep, for custom genomes use the epivizrStandalone package in Bioconductor

**Comment by mschatz** [comment]
Great! Do you have a getting started guide for new species? I imagine you
will need to have the genome annotation and other files prepared in a
specific way.

Thanks!

Mike

**Comment by jkanche** [comment]
Hi Mike,

Epivizr uses Bioconductor data types for handling data. This  [vignette](https://bioconductor.org/packages/release/bioc/vignettes/epivizrStandalone/inst/doc/EpivizrStandalone.html) describes how to use an existing genome with  `epivizrStandalone`.

For new species, you would create a `Seqinfo` object and pass it to `epivizrStandalone`

```
library(GenomicRanges)
library(GenomeInfoDb)
library(epivizrStandalone)

seq <- Seqinfo(seqnames=c("chr1", "chr2", "chrX"),
               seqlengths=c(100000, 10200, 300000),
               isCircular=c(FALSE, FALSE, FALSE),
               genome="custom_genome")

app <- startStandalone(seqinfo = seq)  
```

Please let us know if you have any issues.

Thanks, 
Jayaram
